// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

pub const CAPABILITY_ID: &str = "lenso.jobs@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const JOBS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const JOBS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const CLAIM_OPERATION: &str = "claim";
pub const COMPLETE_OPERATION: &str = "complete";
pub const ENQUEUE_OPERATION: &str = "enqueue";
pub const FAIL_OPERATION: &str = "fail";
pub const INSPECT_OPERATION: &str = "inspect";
pub const RENEW_OPERATION: &str = "renew";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimRequest {
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimResponse {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "lease_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_expires_at: Timestamp,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
}

impl fmt::Debug for ClaimResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ClaimResponse")
            .field("attempt", &self.attempt)
            .field("job_id", &self.job_id)
            .field("kind", &self.kind)
            .field("lease_expires_at", &self.lease_expires_at)
            .field("lease_token", &"<redacted>")
            .field("max_attempts", &self.max_attempts)
            .field("payload", &"<redacted>")
            .field("queue", &self.queue)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ClaimError {
    InvalidQueue,
    NoJobAvailable,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequest {
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
}

impl fmt::Debug for CompleteRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CompleteRequest")
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteResponse {
    #[serde(rename = "completed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteError {
    InvalidLease,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnqueueRequest {
    #[serde(rename = "available_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub available_at: Timestamp,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
}

impl fmt::Debug for EnqueueRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("EnqueueRequest")
            .field("available_at", &self.available_at)
            .field("idempotency_key", &self.idempotency_key)
            .field("kind", &self.kind)
            .field("max_attempts", &self.max_attempts)
            .field("payload", &"<redacted>")
            .field("queue", &self.queue)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnqueueResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EnqueueError {
    IdempotencyConflict,
    InvalidJob,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FailRequest {
    #[serde(rename = "failure_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_code: String,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
    #[serde(rename = "retryable")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retryable: bool,
}

impl fmt::Debug for FailRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("FailRequest")
            .field("failure_code", &self.failure_code)
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .field("retryable", &self.retryable)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FailResponse {
    #[serde(rename = "available_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub available_at: Option<Timestamp>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: FailResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum FailResponseStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum FailError {
    InvalidFailure,
    InvalidLease,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectRequest {
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectResponse {
    #[serde(rename = "attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempts: i64,
    #[serde(rename = "available_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub available_at: Timestamp,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "last_failure_code")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub last_failure_code: OptionalValue<String>,
    #[serde(rename = "lease_expires_at")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub lease_expires_at: OptionalValue<Timestamp>,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: InspectResponseStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InspectResponseStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InspectError {
    JobNotFound,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenewRequest {
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
}

impl fmt::Debug for RenewRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RenewRequest")
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenewResponse {
    #[serde(rename = "lease_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_expires_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RenewError {
    InvalidLease,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct JobsClaim;
impl RequestCapability for JobsClaim {
    type Request = ClaimRequest;
    type Response = ClaimResponse;
    type DomainError = ClaimError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CLAIM_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).claim(context, request)
    }
}

#[derive(Debug)]
pub struct JobsComplete;
impl RequestCapability for JobsComplete {
    type Request = CompleteRequest;
    type Response = CompleteResponse;
    type DomainError = CompleteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != COMPLETE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).complete(context, request)
    }
}

#[derive(Debug)]
pub struct JobsEnqueue;
impl RequestCapability for JobsEnqueue {
    type Request = EnqueueRequest;
    type Response = EnqueueResponse;
    type DomainError = EnqueueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ENQUEUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).enqueue(context, request)
    }
}

#[derive(Debug)]
pub struct JobsFail;
impl RequestCapability for JobsFail {
    type Request = FailRequest;
    type Response = FailResponse;
    type DomainError = FailError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != FAIL_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).fail(context, request)
    }
}

#[derive(Debug)]
pub struct JobsInspect;
impl RequestCapability for JobsInspect {
    type Request = InspectRequest;
    type Response = InspectResponse;
    type DomainError = InspectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INSPECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).inspect(context, request)
    }
}

#[derive(Debug)]
pub struct JobsRenew;
impl RequestCapability for JobsRenew {
    type Request = RenewRequest;
    type Response = RenewResponse;
    type DomainError = RenewError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RENEW_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).renew(context, request)
    }
}

impl serde::Serialize for ClaimError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidQueue => serializer.serialize_str("invalid_queue"),
            Self::NoJobAvailable => serializer.serialize_str("no_job_available"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ClaimError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_queue" => Ok(Self::InvalidQueue),
                "no_job_available" => Ok(Self::NoJobAvailable),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CompleteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidLease => serializer.serialize_str("invalid_lease"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_lease" => Ok(Self::InvalidLease),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for EnqueueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidJob => serializer.serialize_str("invalid_job"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for EnqueueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_job" => Ok(Self::InvalidJob),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for FailError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidFailure => serializer.serialize_str("invalid_failure"),
            Self::InvalidLease => serializer.serialize_str("invalid_lease"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for FailError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_failure" => Ok(Self::InvalidFailure),
                "invalid_lease" => Ok(Self::InvalidLease),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InspectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::JobNotFound => serializer.serialize_str("job_not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InspectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "job_not_found" => Ok(Self::JobNotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RenewError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidLease => serializer.serialize_str("invalid_lease"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RenewError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_lease" => Ok(Self::InvalidLease),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_claim_request(value: &ClaimRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_request(wire: &str) -> Result<ClaimRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_response(value: &ClaimResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_response(wire: &str) -> Result<ClaimResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_error(value: &ClaimError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_error(wire: &str) -> Result<ClaimError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_complete_request(value: &CompleteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request(wire: &str) -> Result<CompleteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_response(value: &CompleteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_response(wire: &str) -> Result<CompleteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_error(value: &CompleteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_error(wire: &str) -> Result<CompleteError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_enqueue_request(value: &EnqueueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_request(wire: &str) -> Result<EnqueueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_enqueue_response(value: &EnqueueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_response(wire: &str) -> Result<EnqueueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_enqueue_error(value: &EnqueueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_error(wire: &str) -> Result<EnqueueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_fail_request(value: &FailRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_request(wire: &str) -> Result<FailRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_fail_response(value: &FailResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_response(wire: &str) -> Result<FailResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_fail_error(value: &FailError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_error(wire: &str) -> Result<FailError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_inspect_request(value: &InspectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_request(wire: &str) -> Result<InspectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_response(value: &InspectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_response(wire: &str) -> Result<InspectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_error(value: &InspectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_error(wire: &str) -> Result<InspectError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_renew_request(value: &RenewRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_renew_request(wire: &str) -> Result<RenewRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_renew_response(value: &RenewResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_renew_response(wire: &str) -> Result<RenewResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_renew_error(value: &RenewError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_renew_error(wire: &str) -> Result<RenewError, serde_json::Error> { decode_portable_json(wire) }

pub trait JobsProvider: fmt::Debug + 'static {
    fn claim(&self, context: InvocationContext, request: ClaimRequest) -> NativeRequestFuture<JobsClaim>;
    fn complete(&self, context: InvocationContext, request: CompleteRequest) -> NativeRequestFuture<JobsComplete>;
    fn enqueue(&self, context: InvocationContext, request: EnqueueRequest) -> NativeRequestFuture<JobsEnqueue>;
    fn fail(&self, context: InvocationContext, request: FailRequest) -> NativeRequestFuture<JobsFail>;
    fn inspect(&self, context: InvocationContext, request: InspectRequest) -> NativeRequestFuture<JobsInspect>;
    fn renew(&self, context: InvocationContext, request: RenewRequest) -> NativeRequestFuture<JobsRenew>;
}

#[derive(Debug)]
struct JobsRequestEndpoint { provider: Rc<dyn JobsProvider> }

#[derive(Debug)]
pub struct JobsEndpoint<P: JobsProvider> { provider: Rc<P>, request_endpoint: JobsRequestEndpoint }
impl<P: JobsProvider> JobsEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn JobsProvider> = provider.clone();
        Self { provider, request_endpoint: JobsRequestEndpoint { provider: request_provider } }
    }
}

impl<P: JobsProvider> NativeRequestEndpoint for JobsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CLAIM_OPERATION,
        COMPLETE_OPERATION,
        ENQUEUE_OPERATION,
        FAIL_OPERATION,
        INSPECT_OPERATION,
        RENEW_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CLAIM_OPERATION => {
                let Ok(request) = request.downcast::<ClaimRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).claim(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            COMPLETE_OPERATION => {
                let Ok(request) = request.downcast::<CompleteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).complete(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            ENQUEUE_OPERATION => {
                let Ok(request) = request.downcast::<EnqueueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).enqueue(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            FAIL_OPERATION => {
                let Ok(request) = request.downcast::<FailRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).fail(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INSPECT_OPERATION => {
                let Ok(request) = request.downcast::<InspectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).inspect(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RENEW_OPERATION => {
                let Ok(request) = request.downcast::<RenewRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).renew(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct JobsClient {
    claim: NativeRequestHandle<JobsClaim>,
    complete: NativeRequestHandle<JobsComplete>,
    enqueue: NativeRequestHandle<JobsEnqueue>,
    fail: NativeRequestHandle<JobsFail>,
    inspect: NativeRequestHandle<JobsInspect>,
    renew: NativeRequestHandle<JobsRenew>,
}
impl JobsClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            claim: dependencies.one::<JobsClaim>()?,
            complete: dependencies.one::<JobsComplete>()?,
            enqueue: dependencies.one::<JobsEnqueue>()?,
            fail: dependencies.one::<JobsFail>()?,
            inspect: dependencies.one::<JobsInspect>()?,
            renew: dependencies.one::<JobsRenew>()?,
        })
    }

    pub async fn claim(&self, request: ClaimRequest) -> Result<ClaimResponse, JobsClaimInvocationError> {
        self.claim.invoke(CLAIM_OPERATION, request).await
            .map_err(JobsClaimInvocationError::Runtime)?
            .map_err(JobsClaimInvocationError::Domain)
    }

    pub async fn claim_with_context(&self, context: InvocationContext, request: ClaimRequest) -> Result<ClaimResponse, JobsClaimInvocationError> {
        self.claim.invoke_with_context(CLAIM_OPERATION, context, request).await
            .map_err(JobsClaimInvocationError::Runtime)?
            .map_err(JobsClaimInvocationError::Domain)
    }

    pub async fn complete(&self, request: CompleteRequest) -> Result<CompleteResponse, JobsCompleteInvocationError> {
        self.complete.invoke(COMPLETE_OPERATION, request).await
            .map_err(JobsCompleteInvocationError::Runtime)?
            .map_err(JobsCompleteInvocationError::Domain)
    }

    pub async fn complete_with_context(&self, context: InvocationContext, request: CompleteRequest) -> Result<CompleteResponse, JobsCompleteInvocationError> {
        self.complete.invoke_with_context(COMPLETE_OPERATION, context, request).await
            .map_err(JobsCompleteInvocationError::Runtime)?
            .map_err(JobsCompleteInvocationError::Domain)
    }

    pub async fn enqueue(&self, request: EnqueueRequest) -> Result<EnqueueResponse, JobsEnqueueInvocationError> {
        self.enqueue.invoke(ENQUEUE_OPERATION, request).await
            .map_err(JobsEnqueueInvocationError::Runtime)?
            .map_err(JobsEnqueueInvocationError::Domain)
    }

    pub async fn enqueue_with_context(&self, context: InvocationContext, request: EnqueueRequest) -> Result<EnqueueResponse, JobsEnqueueInvocationError> {
        self.enqueue.invoke_with_context(ENQUEUE_OPERATION, context, request).await
            .map_err(JobsEnqueueInvocationError::Runtime)?
            .map_err(JobsEnqueueInvocationError::Domain)
    }

    pub async fn fail(&self, request: FailRequest) -> Result<FailResponse, JobsFailInvocationError> {
        self.fail.invoke(FAIL_OPERATION, request).await
            .map_err(JobsFailInvocationError::Runtime)?
            .map_err(JobsFailInvocationError::Domain)
    }

    pub async fn fail_with_context(&self, context: InvocationContext, request: FailRequest) -> Result<FailResponse, JobsFailInvocationError> {
        self.fail.invoke_with_context(FAIL_OPERATION, context, request).await
            .map_err(JobsFailInvocationError::Runtime)?
            .map_err(JobsFailInvocationError::Domain)
    }

    pub async fn inspect(&self, request: InspectRequest) -> Result<InspectResponse, JobsInspectInvocationError> {
        self.inspect.invoke(INSPECT_OPERATION, request).await
            .map_err(JobsInspectInvocationError::Runtime)?
            .map_err(JobsInspectInvocationError::Domain)
    }

    pub async fn inspect_with_context(&self, context: InvocationContext, request: InspectRequest) -> Result<InspectResponse, JobsInspectInvocationError> {
        self.inspect.invoke_with_context(INSPECT_OPERATION, context, request).await
            .map_err(JobsInspectInvocationError::Runtime)?
            .map_err(JobsInspectInvocationError::Domain)
    }

    pub async fn renew(&self, request: RenewRequest) -> Result<RenewResponse, JobsRenewInvocationError> {
        self.renew.invoke(RENEW_OPERATION, request).await
            .map_err(JobsRenewInvocationError::Runtime)?
            .map_err(JobsRenewInvocationError::Domain)
    }

    pub async fn renew_with_context(&self, context: InvocationContext, request: RenewRequest) -> Result<RenewResponse, JobsRenewInvocationError> {
        self.renew.invoke_with_context(RENEW_OPERATION, context, request).await
            .map_err(JobsRenewInvocationError::Runtime)?
            .map_err(JobsRenewInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum JobsClaimInvocationError {
    Domain(ClaimError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsCompleteInvocationError {
    Domain(CompleteError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsEnqueueInvocationError {
    Domain(EnqueueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsFailInvocationError {
    Domain(FailError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsInspectInvocationError {
    Domain(InspectError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsRenewInvocationError {
    Domain(RenewError),
    Runtime(RuntimeFailure),
}
