[package]
name = "lenso-capability-jobs"
version = "0.1.0"
description = "Portable durable Jobs Capability for Lenso applications."
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
futures.workspace = true
lenso-contract-runtime = { version = "0.1.3", git = "https://github.com/LioRael/lenso-protocols", rev = "9769bc5dc828fd9111da6d28a4ecd5f1bb198ab4" }
lenso-kernel = { version = "0.2.0", git = "https://github.com/LioRael/lenso", rev = "cd35675a191d815b690c8889756dfe859a0e4d7b" }
lenso-plugin-authoring = { version = "0.1.1", git = "https://github.com/LioRael/lenso-protocols", rev = "9769bc5dc828fd9111da6d28a4ecd5f1bb198ab4" }
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
lenso-contract-codegen = { version = "0.6.3", git = "https://github.com/LioRael/lenso-protocols", rev = "9769bc5dc828fd9111da6d28a4ecd5f1bb198ab4" }

[lints]
workspace = true
